application:
  window_title: 'Proxima MVP'
  initial_width: 1280
  initial_height: 920
  initial_font_path: './fonts/Delius-Regular.ttf'
  icon: ''
colorscheme:
  core_bg: [100, 100, 100, 255]
fonts:
  header: './fonts/Delius-Regular.ttf'
